---
title: "Results from ESM400 & SOC301 SURVEY"
author: "Jim Yocom"
date: "8/23/2019"
output: html_document
---

```{r setup, include = FALSE}

rm(list = ls())
library(ggplot2)
library(reshape2)
library(Hmisc)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

df <- read.table("R:/fer/rschell/Mozelewski/selfdata.csv", sep = ",", header = FALSE)
colnames(df) <- c("Q1", "Q2", "Q3", "Q4", "SEM")
df


df$CLASS <- ifelse(df$SEM == "AU18" | df$SEM == "AU19", 1, 0)
df$CLASS <- factor(df$CLASS, levels = c(0, 1), labels = c("SOC301", "ES400"))

# Label Questions

Hmisc::label(df$Q1) <- "Compared to your classmates, where would you rank in . . . facilitating a small-group discussion on social inequality?"
Hmisc::label(df$Q2) <- " . . . identifying tasks to do for organizing a social protest?"
Hmisc::label(df$Q3) <- " . . . evaluating whether a work committee is on track or off-track?"
Hmisc::label(df$Q4) <- " . . . assessing a co-worker's work ethic or diligence?"
Hmisc::describe(df)

comment(df$Q1) <- "Facilitating discussion on inequality"
comment(df$Q2) <- "Identifying protest tasks"
comment(df$Q3) <- "Evaluating committee"
comment(df$Q4) <- "Assessing coworker's diligence"

# Ideal median
MD <- median(1:30)

df$Q1 <- as.numeric(df$Q1)
df$Q2 <- as.numeric(df$Q2)
df$Q3 <- as.numeric(df$Q3)
df$Q4 <- as.numeric(df$Q4)

```

# Question 1

```{r}

ggplot(data = df, aes(fill = CLASS)) +  
  geom_density(aes(x = Q1, y = ..scaled..), fill = "black", alpha = 0.05, strata = "scaled") +
  geom_vline(xintercept = median(subset(df, CLASS == "ES400")$Q1), color = "cyan", size = 1) + 
  geom_vline(xintercept = median(subset(df, CLASS == "SOC301")$Q1), color = "salmon", size = 1) + 
  geom_vline(xintercept = 15, color = "black", size = 1) +
  geom_dotplot(alpha = 0.4, aes(x = Q1), color = "black", stackgroups = TRUE) +
  theme_minimal() + 
  scale_x_continuous(limits = c(1, 30), breaks = seq(1, 30, 1), labels = seq(1, 30, 1)) + 
  xlab("Rank") + ggtitle("Facilitating discussion on inequality") +
  theme(axis.line.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```

# Question 2

```{r}
ggplot(data = df, aes(fill = CLASS)) +  
  geom_density(aes(x = Q2, y = ..scaled..), fill = "black", alpha = 0.05) +
  geom_vline(xintercept = median(subset(df, CLASS == "ES400")$Q2), color = "cyan", size = 1) + 
  geom_vline(xintercept = median(subset(df, CLASS == "SOC301")$Q2), color = "salmon", size = 1) +
  geom_vline(xintercept = 15, color = "black", size = 1) +
  geom_dotplot(alpha = 0.4, aes(x = Q2), color = "black", stackgroups = TRUE, binpositions = "all") +
  theme_minimal() + 
  scale_x_continuous(limits = c(1, 30), breaks = seq(1, 30, 1), labels = seq(1, 30, 1)) + 
  xlab("Rank") + ggtitle("Identifying social protest tasks") +
  theme(axis.line.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

```

# Question 3

```{r}
ggplot(data = df, aes(fill = CLASS)) +  
  geom_density(aes(x = Q3, y = ..scaled..), fill = "black", alpha = 0.05) +
  geom_vline(xintercept = median(subset(df, CLASS == "ES400")$Q3), color = "cyan", size = 1) + 
  geom_vline(xintercept = median(subset(df, CLASS == "SOC301")$Q3), color = "salmon", size = 1) + 
  geom_vline(xintercept = 15, color = "black", size = 1) +
  geom_dotplot(alpha = 0.4, aes(x = Q3), color = "black", stackgroups = TRUE) +
  theme_minimal() + 
  scale_x_continuous(limits = c(1, 30), breaks = seq(1, 30, 1), labels = seq(1, 30, 1)) + 
  xlab("Rank") + ggtitle("Evaluating a committee") +
  theme(axis.line.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

```

# Question 4

```{r}
ggplot(data = df, aes(fill = CLASS)) +  
  geom_density(aes(x = Q4, y = ..scaled..), fill = "black", alpha = 0.05, stata = "scaled") +
  geom_vline(xintercept = median(subset(df, CLASS == "ES400")$Q4), color = "cyan", size = 1) + 
  geom_vline(xintercept = median(subset(df, CLASS == "SOC301")$Q4), color = "salmon", size = 1) + 
  geom_vline(xintercept = 15, color = "black", size = 1) +
  geom_dotplot(alpha = 0.4, aes(x = Q4), color = "black", stackgroups = TRUE) +
  theme_minimal() + 
  scale_x_continuous(limits = c(1, 30), breaks = seq(1, 30, 1), labels = seq(1, 30, 1)) + 
  xlab("Rank") + ggtitle("Asessing a co-worker's diligence") +
  theme(axis.line.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```

